# Generated by Django 4.2.4 on 2024-07-22 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='messages',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='messages_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
