# Generated by Django 4.2.4 on 2024-07-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_messages_options_messages_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='likes',
        ),
    ]
